api/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('loremipsum/', views.get_lorem_ipsum_content),
    path('submitcontact/', views.post_contact_message)
]

home/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'
urlpatterns = [
    path('', views.return_home, name='home'),
    path('contact/', views.return_contact, name='contact')
]

takehome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from takehome.settings import STATIC_URL


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', 'home')),
    path('contact/', include('home.urls', 'contact')),
    path('api/', include('api.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.


class Contact(models.Model):
    firstName = models.CharField(max_length=120)
    lastName = models.CharField(max_length=120)
    title = models.CharField(max_length=250, null=True)
    email = models.EmailField(null=True)
    message = models.TextField()


class LoremIpsum(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField()
    img = models.URLField()

api/views.py
import json
# from django.http import JsonResponse
from django.forms.models import model_to_dict
from home.models import LoremIpsum, Contact
from rest_framework.response import Response
from rest_framework.decorators import api_view
from home.serializers import ContactSerializer, LoremIpsumSerializer

@api_view(["GET"])
def get_lorem_ipsum_content(request, *args, **kwargs):
    instance = LoremIpsum.objects.all()
    data = {}
    if instance:
        data = [LoremIpsumSerializer({'id' : item.id, 'title' : item.title, 'text' : item.text, 'img' : item.img}).data for item in instance]
        #data = LoremIpsumSerializer(instance).data
    return Response(data)

@api_view(["POST"])
def post_contact_message(request, *args, **kwargs):
    serializer =  ContactSerializer(data=request.data)
    if serializer.is_valid():
        data = serializer.save()
        return Response(serializer.data)

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
import requests
import json

# Create your views here.

def return_home(request):
    endpoint = 'http://localhost:8000/api/loremipsum/'
    get_response = requests.get(endpoint)
    data = json.loads(get_response.text)
    return render(request, 'home.html', {'listData': data})

def return_contact(request):
    return render(request, 'contact.html')

home/templates/contact.html
<!doctype html>
<html lang="en">
    {% include "head.html" %}
  <body class="main_body" id="contact-body">
    {% include "navbar.html" %}
    <div class="contact-body">
        <h1 class="contact-body-head">Heading One</h1>
        <div class="contact-body-par">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do dos eiusmod tempor incididunt ut labore et trace dolore manga aliqua.</p>
            <p>Proin sagittis nisl rhoncus mattis rhoncus. at augue eget arcu dictum varius duis at consectetur lorem.</p>
        </div>
    </div>
    <div class="contact-form">
      <form name="contactform" id="contactform">

        <h2 class="contact-form-head">Heading Two</h2>
        <div class="row" id="con-form-ent">
          <div class="col">
            <input name="firstName" type="text" class="form-control" placeholder="First name" aria-label="First name" >
          </div>
          <div class="col">
            <input name="lastName" type="text" class="form-control" placeholder="Last name" aria-label="Last name" >
          </div>
        </div>
        <div class="row" id="con-form-ent">
          <div class="col">
            <input name="title" type="text" class="form-control" placeholder="Title" aria-label="Title" >
          </div>
          <div class="col">
            <input name="email" id="emailfield" type="email" class="form-control" placeholder="Email" aria-label="Email" >
          </div>
        </div>
        <div class="row" id="con-form-mes">
          <input name="message" type="text" class="form-control" placeholder="Message" aria-label="Message" >  
        </div>
        <div class="card-body-btn" id="con-form-sub">
          <input name="send" id="submitbtn" type="submit" class="btn btn-primary" value="Submit">
        </div>
      </form>
    </div>
    {% include "scripts.html" %}
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script>
      $(document).ready(function(){

        console.log('in the main function');

        var frm = $('#contactform');
        frm.submit(function (ev) {
          $.ajax({
            type: 'post',
            url: 'http://localhost:8000/api/submitcontact/',
            data: getFormData(frm),
            success: function(data) {
              alert('Successfully submitted form data');
              frm.find('input:text').val('');
              $('#emailfield').val('');
            }
          });
          ev.preventDefault();

        });

        function getFormData($form) {
        var unindexed_array = $form.serializeArray();
        var indexed_array = {};

        $.map(unindexed_array, function(n, i) {
          indexed_array[n['name']] = n['value'];
        });

        console.log(indexed_array);

        return indexed_array;
        }

      });

      
      


    </script>
    
  </body>
</html>

home/templates/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/superbass.css' %}" type="text/css" />
</head>

home/templates/home.html
{% load static %}
<!doctype html>
<html lang="en">
    {% include "head.html" %}
  <body class="main_body">
    {% include "navbar.html" %}
    <div class="cardsection">
      {%for item in listData %}
      <div class="card">
        <div class="card-img-div">

          <img src="{{ item.img }}" class="card-img-top" alt="...">
        </div>
        <div class="card-body">
          <div class="card-body-text">

            <h2 class="card-title">{{ item.title }}</h2>
            <p class="card-text">{{ item.text }} </p>
          </div>
          <div class="card-body-btn">

            <a href="#" class="btn btn-primary">Learn More</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="par-body" id="par-body-script-challenge">

      <h1 class="head-one">Heading One</h1>
      <p class="par-body-text" >Remove the duplicates in 2 Javascript arrays (found in readme), add the results to an array and output the list of distinct names in an unordered list below this paragraph when <a href="javascript:sortNames()">this link</a> is clicked.
        If the operation has been completed already, notify the user that this as already been done.</p>
    </div>
        {% include "scripts.html" %}
        <script>
          var filteredNames = [];
          const names1 = ['Matt Johnson', 'Matt Johnson', 'Bart Paden', 'Ryan Doss', 'Jared Malcolm'];
          const names2 = ['Matt Johnson', 'Bart Paden', 'Bart Paden', 'Jordan Heigle', 'Jordan Heigle', 'Tyler Viles'];

          const allNames = names1.concat(names2); 
          
          function sortNames() {
            var parBody = document.getElementById('par-body-script-challenge');

            if (filteredNames === undefined || filteredNames.length == 0) {
              filteredNames = [...new Set(allNames)];

              var newNamePar = document.createElement('P');
              filteredNames.forEach(function(name, i) {
                if(i === filteredNames.length-1) {

                  var newName = document.createTextNode(name);
                }else {
                  var newName = document.createTextNode(name + ', ');
                }
                newNamePar.appendChild(newName);   
              });
              
              newNamePar.id = 'name-challenge-par'
              newNamePar.style.cssText = 'color: white; margin-left: 4%;'
              parBody.appendChild(newNamePar);
            } else {

              alert("This operation has already been done.");
            }

          }

        </script>
  </body>
</html>

home/templates/navbar.html
{% load static %}
<nav class="navbar navbar-dark bg-transparent">

<div id="logodiv">
  <img class="navlogo" src="{% static 'logos/Logo.png'" %}">
</div>
<div id="navdiv">

</div>
 <script>
   var nav = document.getElementById("navdiv");
   var navclick = document.createElement("a");

   var cururl = new URL(window.location.href).toString();

   if(cururl.includes('contact')) {
    navclick.setAttribute('href', 'home:home');
     navclick.href = "{% url 'home:home' %}";
     navclick.textContent = 'Home';
   } else {
    navclick.setAttribute('href', 'contact');
     navclick.href = "{% url 'home:contact' %}";
     navclick.textContent = 'Contact';
   }

   navclick.id = 'navhref';

   nav.appendChild(navclick);

 </script>

</nav>

home/templates/scripts.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>